Internal Server Error: /guardar_selecciones/
Traceback (most recent call last):
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'usuario_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\servicio\views.py", line 422, in guardar_selecciones
    cursor.execute(insert_query, [
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'usuario_id' cannot be null")
"POST /guardar_selecciones/ HTTP/1.1" 500 154900
Internal Server Error: /guardar_selecciones/
Traceback (most recent call last):
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'usuario_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\servicio\views.py", line 422, in guardar_selecciones
    cursor.execute(insert_query, [
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\Franc\Desktop\ProyectoRestaurant\Casino\venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'usuario_id' cannot be null")
"POST /guardar_selecciones/ HTTP/1.1" 500 155076
